// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Atcommands
 * Place the definition of custom atcommands in this file.
 * Format:
 *	ACMD_DEF(command_name),
 **/

//ACMD_DEF(newcommand),
	ACMD_DEF(listenbg),
	ACMD_DEF(order),
	ACMD_DEF(leader),
	ACMD_DEF(reportafk),
	ACMD_DEF(guildskill),
	ACMD_DEF(bgrank),
	ACMD_DEF(woerank),
	ACMD_DEF(bgstats),
	ACMD_DEF(woestats),